name: Testing
on: push

jobs:
  test_stringql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        pip install testing.postgresql
        python3 stringql/pg_engine_test.py test