name: Testing
on: push

jobs:
  test_stringql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        pip3 install testing.postgresql
        pip3 install psycopg2-binary
        python3 -m unittest test_sringql.py -v