name: Testing
on: push

jobs:
  test_stringql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        sudo apt-get install python3-setuptools
        sudo apt install libpq-dev python3-dev
        pip3 install testing.postgresql
        pip3 install psycopg2
        python3 stringql/pg_engine_test.py test